### ISSUE TITLE
Bug Report: StoryBoard Mutliple Select Causes Crash

### ISSUE THREAD

**Issue by reptile18** [act-org/dls#129]
**Describe the bug**
In the DLS playground, when trying to change the select's multiple property to true, an error is displayed. This is due to the type of value needing to be an array, but only one property can be changed at a time.

**To Reproduce**
In the playground, select Select, then choose Controls, and set multiple to true.

**Expected behavior**
The preview pane should update appropriately.

**Comment by joncursi** [comment]
Fixed via https://github.com/act-org/dls/pull/130
